package com.fgogotran.localization

/**
 * English translations for legacy UI strings that are still hard-coded in Kotlin.
 *
 * This is a migration bridge for the English UI phase. New UI should use Android string
 * resources; keep this map limited to user-visible UI text and remove entries as screens
 * are migrated to values-en.
 */
internal object EnglishUiText {
    private val exact = mapOf(
        "；语气增强 API 失败" to "; AI expression API failed",
        "（语气增强已开启）" to "(AI expression on)",
        "\${tenths / 10}.\${tenths % 10} 秒" to "\${tenths / 10}.\${tenths % 10} s",
        "\$safeCount 幕" to "\$safeCount scenes",
        "大" to "Large",
        "大小" to "Size",
        "女" to "Female",
        "小" to "Small",
        "已开启，未连接" to "Enabled, not connected",
        "已开启" to "Enabled",
        "已生成 TXT" to "TXT generated",
        "已关闭优化" to "Off",
        "已关闭实时语音屏幕捕获" to "Live voice screen capture stopped",
        "已启用" to "Enabled",
        "已连接" to "Connected",
        "已保存；中国 Azure 实时翻译还需填写资源端点" to "Saved; China Azure live translation still needs a resource endpoint",
        "已保存" to "Saved",
        "已恢复默认位置" to "Default position restored",
        "已授权" to "On",
        "已清空" to "Cleared",
        "已清除 \$count 条缓存" to "Cleared \$count cache entries",
        "不支持" to "Unsupported",
        "不用一直换模式，先按自己的阅读习惯选一个。" to "You do not need to switch modes constantly. Pick one that matches how you read.",
        "不会上传" to "Never uploaded",
        "中文" to "Chinese",
        "中国 Azure Speech 资源端点" to "China Azure Speech resource endpoint",
        "中国 Azure" to "China Azure",
        "中国站" to "China",
        "云端接口一次只启用一个参数；开启另一项会自动关闭当前项。" to "Cloud APIs allow only one sampling parameter at a time; enabling another turns the current one off.",
        "仅保存在本机，用于 AI 语音朗读和已启用的实时语音翻译。" to "Stored only on this device for AI voice playback and live voice translation when enabled.",
        "分享错误纪录" to "Share diagnostic log",
        "区域翻译" to "Area",
        "开启：调用 API 分析本句情绪、语速、音高，并临时匹配语音；新角色也可尝试播放。\n关闭：只用本机规则和已收录语音；更快、更稳定，但新角色需等数据库更新后才有语音。" to "On: calls the API to analyze emotion, speed, and pitch, then temporarily matches a voice; new characters may also be tried.\nOff: uses only local rules and installed voices; faster and more stable, but new characters need a database update before voice is available.",
        "开启" to "On",
        "手动" to "Manual",
        "手动或半自动点击后，本次识别/翻译未成功，可再点一次。" to "After a manual or semi-auto tap, if recognition or translation failed, you can tap again.",
        "手动检查新版本" to "Check for updates",
        "手動翻譯" to "Manual translation",
        "支持" to "Supported",
        "文字送り / 表示速度" to "Text speed: 文字送り / 表示速度",
        "无法连接服务器，请检查电脑 IP、端口、防火墙和 VPN 的局域网放行设置" to "Cannot reach the server. Check the PC IP, port, firewall, and VPN/LAN settings.",
        "无障碍服务" to "Accessibility service",
        "无障碍服务未启用" to "Accessibility service is off",
        "无障碍服务未连接" to "Accessibility service is not connected",
        "无障碍服务用途说明" to "Accessibility service purpose",
        "日文原文" to "Japanese original",
        "日服" to "JP server",
        "日服译文语言" to "Translation language",
        "半" to "S",
        "半自动" to "Semi-auto",
        "半自动阅读，点击按钮翻译选项。" to "Semi-auto reading. Tap the button to translate choices.",
        "半自動翻譯" to "Semi-auto translation",
        "去设置" to "Go to Settings",
        "去授权 →" to "Grant permission →",
        "去管理 →" to "Manage →",
        "发布日期：\${releaseDate.substringBefore('T')}" to "Release date: \${releaseDate.substringBefore('T')}",
        "发现新版本" to "Update available",
        "句読点待ち時間 / 标点等待时间" to "Punctuation wait: 句読点待ち時間",
        "可用于 FgoGotran 翻译；接口不接受 \$ignoredLabels，已自动忽略" to "Works with FgoGotran translation; unsupported parameters ignored: \$ignoredLabels",
        "可用于 FgoGotran 翻译" to "Ready for FgoGotran translation",
        "可选稳定性（非必要）" to "Optional stability settings",
        "失败" to "Failed",
        "打开 FgoGotran 网站" to "Open FgoGotran website",
        "打开语音设置" to "Open voice settings",
        "打开错误纪录" to "Open diagnostic log",
        "未开启" to "Off",
        "未启用" to "Disabled",
        "未授予屏幕捕获授权" to "Screen capture permission not granted",
        "未授权" to "Not granted",
        "本地 HTTP 不加密，仅应在可信 Wi-Fi 中使用；请保留 API Key 认证。" to "Local HTTP is unencrypted. Use it only on trusted Wi-Fi and keep API Key authentication enabled.",
        "本地／自定义接口可单独启用，也可同时发送两个参数。" to "Local/custom endpoints can enable either parameter or send both.",
        "正在生成测试语音..." to "Generating test voice...",
        "用于调试和排查问题。" to "For debugging and troubleshooting.",
        "由“设置 → 御主性别”决定" to "Determined by Settings → Master gender",
        "电池优化" to "Battery optimization",
        "电池优化可能限制后台服务" to "Battery optimization may restrict background services",
        "目前没有错误纪录。" to "No diagnostic events yet.",
        "立即更新" to "Update now",
        "记录" to "Log",
        "优化中" to "Optimization on",
        "先调 FGO 文字速度" to "Set FGO text speed first",
        "全" to "A",
        "全自动" to "Auto",
        "全自动运行；此模式下点击按钮不会手动翻译。" to "Full-auto is on; tapping the button will not translate manually.",
        "全自動翻譯" to "Full-auto translation",
        "全球 Azure" to "Global Azure",
        "关闭 FgoGotran 无障碍服务 → 等 2–3 秒 → 重新开启；若仍失败请重启模拟器" to "Turn off FgoGotran accessibility → wait 2–3 seconds → turn it back on; restart the emulator if it still fails",
        "关闭" to "Close",
        "关闭服务" to "Close service",
        "同时显示游戏原文" to "Show original game text",
        "字幕大小" to "Subtitle size",
        "导出 TXT" to "Export TXT",
        "导出失败" to "Export failed",
        "当前" to "Current",
        "当前服务商需要 API Key" to "The current provider requires an API Key",
        "当前版本：\$currentVersionName" to "Current version: \$currentVersionName",
        "当前版本" to "Current version",
        "当前御主性别" to "Current Master gender",
        "当前模型 Sakura 不支持 AI 语气增强，将自动使用本机语气规则。切换到其他模型后会恢复已保存的选择。" to "The current Sakura model does not support AI expression. Local expression rules will be used; switching models restores your saved choice.",
        "当前模型不支持" to "Current model not supported",
        "成功" to "Success",
        "收起高级自定义" to "Hide advanced settings",
        "有角色名对话" to "Named dialogue",
        "此版本不再提醒" to "Skip this version",
        "红色外圈" to "Red ring",
        "自动：关闭随机采样；翻译输出更稳定。" to "Auto: disables random sampling for more stable translations.",
        "自动：当前 GPT 模型不发送采样参数，避免请求被拒绝。" to "Auto: does not send sampling parameters for this GPT model to avoid rejected requests.",
        "自动：当前 GPT 模型使用 Temperature 0.3。" to "Auto: uses Temperature 0.3 for this GPT model.",
        "自动：使用本地模型或兼容接口的默认采样参数。" to "Auto: uses the local or compatible endpoint's default sampling parameters.",
        "自动：使用当前 Qwen 模型的默认采样参数。" to "Auto: uses the current Qwen model's default sampling parameters.",
        "自动：Claude 使用模型默认值，不发送采样参数。" to "Auto: Claude uses model defaults and sends no sampling parameters.",
        "自动：Gemini 使用模型默认值，不发送采样参数。" to "Auto: Gemini uses model defaults and sends no sampling parameters.",
        "自动：Temperature \${SettingsRepository.DEFAULT_DEEPSEEK_TEMPERATURE}；不发送 Top-p。" to "Auto: Temperature \${SettingsRepository.DEFAULT_DEEPSEEK_TEMPERATURE}; no Top-p.",
        "自动（推荐）" to "Auto (recommended)",
        "自动显示全部最近问题：错误、权限阻塞、资料更新失败、缺少语音档案、临时语音 API 建立结果。" to "Shows all recent issues: errors, permission blocks, data update failures, missing voice profiles, and temporary voice API setup results.",
        "自定义" to "Custom",
        "设置 →" to "Settings →",
        "设置" to "Settings",
        "设置位置" to "Location",
        "启用实时语音字幕" to "Enable live voice subtitles",
        "启用语音" to "Enable voice",
        "启用缓存" to "Enable cache",
        "启动服务" to "Start service",
        "启动服务被阻止：FgoGotran 没有收到无障碍服务连接" to "Start blocked: FgoGotran did not receive an accessibility service connection",
        "启动服务被阻止" to "Start blocked",
        "应用未允许本地 HTTP，请安装支持本地 AI 的新版 APK" to "This app does not allow local HTTP. Install a newer APK with local AI support.",
        "应用API设置" to "Apply API settings",
        "快" to "Fast",
        "我同意并前往设置" to "I agree, open Settings",
        "找不到瑪修语音档，请先更新语音资料" to "Mash voice profile not found. Update voice data first.",
        "更新内容" to "What's new",
        "状态：\$status\n用时：\${formatApiResponseTime(durationMs)}\n结果：\$result" to "Status: \$status\nTime: \${formatApiResponseTime(durationMs)}\nResult: \$result",
        "状态" to "Status",
        "状态无法确认" to "Status unknown",
        "玛修·基列莱特，在此。御主……战斗准备完成，请下达指示。" to "Mash Kyrielight, reporting. Master... combat preparation complete. Awaiting your orders.",
        "玛修" to "Mash",
        "男" to "Male",
        "系统默认" to "System default",
        "使用与御主性别对应的语音。" to "Use the voice matching the Master's gender.",
        "使用双语剧情上下文" to "Use bilingual story context",
        "使用对应角色语音。" to "Use the matching character voice.",
        "使用指南" to "Guide",
        "使用范围" to "Scope",
        "使用旁白语音。" to "Use the narrator voice.",
        "例：藤丸立香" to "Example: Fujimaru Ritsuka",
        "参考场景数" to "Context scenes",
        "取消" to "Cancel",
        "国际站" to "International",
        "图片、截图、录屏、视频源，或其他应用里的 FGO 素材翻译。" to "Images, screenshots, screen recordings, video sources, or FGO assets in other apps.",
        "实时字幕" to "Live subtitles",
        "实时字幕屏幕捕获已启动" to "Live subtitle screen capture started",
        "实时字幕屏幕捕获未能启动" to "Live subtitle screen capture failed to start",
        "实时字幕预览" to "Live subtitle preview",
        "实时语音已停止，OCR 翻译继续使用无障碍截图" to "Live voice stopped; OCR translation continues with accessibility screenshots",
        "实时语音字幕" to "Live voice subtitles",
        "实时语音需要屏幕捕获授权；OCR 翻译不受影响" to "Live voice needs screen capture permission; OCR translation is unaffected",
        "实时语音翻译" to "Live voice translation",
        "实时翻译使用 Azure 门户中该 Speech 资源的根端点；仅接受 HTTPS 的 *.cognitiveservices.azure.cn。" to "Live translation uses the root endpoint of that Speech resource in the Azure portal; only HTTPS *.cognitiveservices.azure.cn is accepted.",
        "服务仍会尝试启动，但部分手机或模拟器可能会中断悬浮窗" to "The service will still try to start, but some phones or emulators may stop the overlay.",
        "服务商" to "Provider",
        "服务商返回错误：\${message.take(160)}" to "Provider error: \${message.take(160)}",
        "注意" to "Note",
        "表现调节" to "Expression tuning",
        "该服务商或模型为保证请求兼容性，仅使用自动模式。" to "This provider or model uses Auto mode only for request compatibility.",
        "返回" to "Back",
        "进阶引擎。准确度高，识别范围广。依赖 CPU 算力。" to "Advanced engine. High accuracy and broad recognition, but CPU-intensive.",
        "连接模型超时，请确认电脑端模型已加载完成" to "Timed out connecting to the model. Make sure the PC-side model has finished loading.",
        "采样开关" to "Sampling",
        "保存 Azure 设置" to "Save Azure settings",
        "保存" to "Save",
        "保存失败" to "Save failed",
        "前台测试已开启" to "Foreground test enabled",
        "前台检测已恢复正常" to "Foreground detection restored",
        "屏幕捕获已被系统停止" to "Screen capture stopped by the system",
        "恢复默认" to "Reset to default",
        "按角色朗读剧情台词。" to "Read story dialogue by character.",
        "按钮文字会显示当前模式，长按可打开翻译菜单。" to "The button label shows the current mode. Long-press to open the translation menu.",
        "显示在其他应用上层" to "Display over other apps",
        "显示在其他应用上层权限未开启" to "Display over other apps permission is off",
        "查看本次识别和翻译历史。" to "View this session's OCR and translation history.",
        "查看完整教程、下载页面和最新信息。" to "View the full guide, downloads, and latest information.",
        "标准" to "Standard",
        "测试 API" to "Test API",
        "测试中..." to "Testing...",
        "测试中" to "Testing",
        "测试失败，请检查模型和网络连接" to "Test failed. Check the model and network connection.",
        "测试失败：\${error::class.java.simpleName}" to "Test failed: \${error::class.java.simpleName}",
        "测试失败：\${message.take(96)}" to "Test failed: \${message.take(96)}",
        "测试例句：玛修・基列莱特，在此。御主……战斗准备完成，请下达指示。" to "Test sentence: Mash Kyrielight, reporting. Master... combat preparation complete. Awaiting your orders.",
        "测试语音" to "Test voice",
        "测试语音已播放\$apiStatus" to "Test voice played\$apiStatus",
        "点击按钮翻译当前画面。" to "Tap the button to translate the current screen.",
        "相同原文可直接使用上次翻译，速度更快；\n遇到旧译文时可以清除缓存。" to "Identical source text reuses the previous translation for speed.\nClear the cache if you see stale translations.",
        "看懂悬浮按钮" to "Floating button guide",
        "若 Android 已显示开启，请关闭 FgoGotran 无障碍服务后重新开启" to "If Android shows it as on, turn off the FgoGotran accessibility service and turn it back on.",
        "范围 0.00–1.00；数值越低越稳定" to "Range 0.00–1.00; lower values are more stable.",
        "范围 0.01–1.00；数值越低候选范围越小" to "Range 0.01–1.00; lower values narrow the candidate pool.",
        "语气增强" to "AI expression",
        "语言" to "Language",
        "语音设置" to "Voice settings",
        "语音朗读" to "Voice playback",
        "语速" to "Speed",
        "重新开启实时语音时会重新申请屏幕捕获授权" to "Re-enabling live voice will request screen capture permission again.",
        "重置字幕位置" to "Reset subtitle position",
        "限制候选词范围" to "Limit candidate range",
        "音量" to "Volume",
        "兼容 OpenAI Chat Completions；支持可信局域网内的本地模型" to "OpenAI Chat Completions compatible; supports local models on trusted LANs.",
        "剧情文字完整显示后，OCR 和自动翻译会更稳定。" to "OCR and auto-translation are more stable after the dialogue text is fully displayed.",
        "捕获播放的日语语音，直接通过 Azure 显示中文流式字幕。" to "Captures playing Japanese audio and shows Chinese streaming subtitles via Azure.",
        "旁白／无名对白" to "Narration / unnamed dialogue",
        "朗读" to "Voice",
        "朗读文本" to "Read text",
        "朗读范围" to "Playback scope",
        "朗读模式" to "Voice mode",
        "朗读模式（未开启）" to "Voice mode (off)",
        "站点" to "Site",
        "请求设置" to "Request settings",
        "请使用对应站点的 API Key。" to "Use an API Key for the matching site.",
        "请前往下载页面查看更新内容。" to "Open the download page to see what's new.",
        "请检查 API Key" to "Check the API Key",
        "调试日志已开启" to "Debug logging enabled",
        "调试日志已关闭" to "Debug logging disabled",
        "较大" to "Large",
        "较小" to "Small",
        "适合剧情阅读。对话自动刷新；遇到选项时，再点悬浮按钮翻译选项。" to "Best for story reading. Dialogue refreshes automatically; tap the floating button when choices appear.",
        "适合菜单、公告、漏识别画面。框选区域会重新翻译。" to "Best for menus, announcements, and missed screens. The selected area is translated again.",
        "适合想完全掌控节奏的你。点 GO 后翻译当前画面。" to "Best if you want full control. Tap GO to translate the current screen.",
        "适合想轻松阅读的你。应用会尽量自动刷新对话和选项。" to "Best for relaxed reading. The app refreshes dialogue and choices automatically when possible.",
        "选择适合的 OCR（光学字元识别）引擎" to "Choose the OCR engine",
        "选择阅读方式" to "Choose a reading mode",
        "高级自定义" to "Advanced settings",
        "停止服务" to "Stop service",
        "御主名称" to "Master name",
        "御主性别" to "Master gender",
        "御主选项" to "Master choices",
        "悬浮按钮" to "Floating button",
        "悬浮窗权限未授权" to "Overlay permission not granted",
        "悬浮窗权限用途说明" to "Overlay permission purpose",
        "控制随机程度" to "Control randomness",
        "检查中" to "Checking",
        "检查版本" to "Check for updates",
        "清空" to "Clear",
        "清除中" to "Clearing",
        "清除缓存" to "Clear cache",
        "清除缓存失败" to "Failed to clear cache",
        "维护" to "Maintenance",
        "最大" to "Max",
        "最新版本：\${update.versionName}" to "Latest version: \${update.versionName}",
        "提示：可选全球 Azure；中国 Azure 需要组织/工作/学校账号，个人 Microsoft 账号不能登录使用。" to "Note: Global Azure is optional; China Azure requires an organization/work/school account and cannot be used with a personal Microsoft account.",
        "提供最近场景的日文与中文对照；模型误译前文时可关闭；会增加Token消耗(云端API)" to "Provides recent scene context in Japanese and Chinese; disable if the model misreads earlier text; increases token usage on cloud APIs.",
        "暂不更新" to "Not now",
        "暂无翻译LOG。" to "No log yet.",
        "裁切翻譯" to "Crop translation",
        "裁剪" to "Crop",
        "隐私与统计" to "Privacy & analytics",
        "简中服" to "CN server",
        "简体中文" to "Simplified Chinese",
        "跟随系统设置" to "Follow system settings",
        "错误" to "Error",
        "错误纪录" to "Diagnostic log",
        "慢" to "Slow",
        "截图、游戏文本、译文、API Key、玩家名、账号信息或设备识别码。" to "Screenshots, game text, translations, API keys, player names, account information, or device identifiers.",
        "瑪修・基列萊特，在此。御主……戰鬥準備完成，請下達指示。" to "Mash Kyrielight, reporting. Master... combat preparation complete. Awaiting your orders.",
        "瑪修" to "Mash",
        "管理接口" to "Manage API",
        "播放声音捕获权限未授权" to "Playback audio capture permission not granted",
        "模式" to "Mode",
        "模型" to "Model",
        "模型不兼容 FgoGotran 翻译格式" to "The model is incompatible with FgoGotran's translation format",
        "模型名称" to "Model name",
        "模型没有按 FgoGotran 翻译格式返回中文" to "The model did not return Chinese in FgoGotran's translation format",
        "模型或请求参数不被服务商接受：\${message.take(160)}" to "Provider rejected the model or request parameters: \${message.take(160)}",
        "模型返回为空" to "Model returned an empty response",
        "额度或频率限制异常：\${message.take(160)}" to "Quota or rate limit issue: \${message.take(160)}",
        "战" to "B",
        "戰" to "Battle",
        "BATTLE 字幕模式：仅翻译战斗字幕区域；长按悬浮按钮打开菜单后选择。" to "BATTLE subtitle mode: translates only battle subtitles. Long-press the floating button and choose it from the menu.",
        "默认引擎。启动快，耗电低。由 Google ML Kit 在本机识别。" to "Default engine. Fast startup and low power use. Recognizes on-device with Google ML Kit.",
        "默认关闭：送翻译前会移除〈…〉注音，注音有时会干扰翻译质量；需要读音提示时可打开" to "Off by default: ruby annotations are removed before translation because they can hurt quality. Enable if you need reading hints.",
        "繁中服" to "TW server",
        "繁體中文" to "Traditional Chinese",
        "翻译 + 朗读" to "Translate + voice",
        "翻译 + 朗读模式" to "Translate + voice mode",
        "翻译时包含注音〈ruby〉" to "Include ruby annotations when translating",
        "翻译偏好" to "Translation preferences",
        "翻译悬浮窗正在运行" to "Translation overlay is running",
        "翻译缓存" to "Translation cache",
        "翻译模式" to "Translation mode",
        "翻译LOG" to "Log",
        "AI 语气增强" to "AI expression",
        "AI 语音朗读" to "AI voice playback",
        "Android 使用 RECORD_AUDIO 权限保护其他应用的播放声音捕获" to "Android uses the RECORD_AUDIO permission to protect playback capture from other apps",
        "API 地址" to "API address",
        "API接口" to "API",
        "Azure 区域" to "Azure region",
        "Azure 语音请求失败：\${message.take(96)}" to "Azure voice request failed: \${message.take(96)}",
        "Azure Key 无效，或当前区域不可用" to "The Azure key is invalid, or the current region is unavailable",
        "Azure Speech Key 为空" to "Azure Speech key is empty",
        "BATTLE字幕" to "BATTLE subtitles",
        "BATTLE字幕模式，长按切换模式" to "BATTLE subtitle mode. Long-press to switch modes.",
        "FGO 日文故事 → 中文即时翻译" to "FGO Japanese story → Chinese live translation",
        "FGO 服务器" to "FGO server",
        "FGO 游戏内实时画面、剧情、选项，以及裁剪模式框选的画面区域。" to "FGO live gameplay, story, choices, and areas selected in crop mode.",
        "FgoGotran 只收集匿名使用统计，用来了解版本、模式和 API 类型的使用情况。" to "FgoGotran collects only anonymous usage statistics to understand version, mode, and API-type usage.",
        "FgoGotran 网站" to "FgoGotran website",
        "FgoGotran 服务中" to "FgoGotran service running",
        "FgoGotran 的翻译只在正在运行的 FGO 画面上生效。" to "FgoGotran translations only work on the running FGO screen.",
        "FgoGotran 错误纪录" to "FgoGotran diagnostic log",
        "HTTP 仅允许" to "HTTP only allows",
        "HTTP 地址必须使用私有局域网数字 IP，并指向 /chat/completions。" to "HTTP addresses must use a private LAN numeric IP and point to /chat/completions.",
        "HTTPS 可连接任意服务；HTTP 仅允许数字形式的私有局域网 IP" to "HTTPS can connect to any service; HTTP only allows numeric private LAN IPs.",
        "https://资源名.cognitiveservices.azure.cn" to "https://resource-name.cognitiveservices.azure.cn",
        "MediaProjection 已启动" to "MediaProjection started",
        "MediaProjection 启动失败" to "MediaProjection failed to start",
        "OCR 引擎" to "OCR engine",
        "OCR 翻译不受影响；请重新开启实时语音并允许屏幕捕获授权" to "OCR translation is unaffected; re-enable live voice and allow screen capture permission.",
        "OCR 翻译仍会启动，实时语音翻译不会启动" to "OCR translation will still start; live voice translation will not.",
        "Sakura：本机规则" to "Sakura: local rules",
        "Temperature 必须在 0.00 到 1.00 之间" to "Temperature must be between 0.00 and 1.00",
        "Top-p 必须在 0.01 到 1.00 之间" to "Top-p must be between 0.01 and 1.00",
        "ページ送り / 表示速度" to "Page turn: ページ送り / 表示速度",
        "マイルーム → ゲームオプション → テキスト表示速度\n我的房间 → 游戏选项 → 文本显示速度" to "My Room → Game Options → Text Display Speed\nマイルーム → ゲームオプション → テキスト表示速度",
        "截图失败" to "Screenshot failed",
        "区域太小" to "Selected area is too small",
        "未识别到文字" to "No text recognized",
        "翻译失败" to "Translation failed",
        "屏幕捕获未就绪：请回到 FGO 横屏画面后，重新启动悬浮服务并允许屏幕捕获授权" to "Screen capture is not ready: return to the FGO landscape screen, restart the floating service, and allow screen capture",
        "未授予播放声音捕获权限" to "Playback audio capture permission is not granted",
        "当前设备架构不受 Azure Speech SDK 支持" to "This device architecture is not supported by the Azure Speech SDK",
        "Azure Speech Key 为空" to "Azure Speech Key is empty",
        "中国 Azure 资源端点无效" to "China Azure resource endpoint is invalid",
        "实时语音翻译正在连接…" to "Live voice translation is connecting…",
        "Android 无法开始捕获游戏播放声音" to "Android cannot start capturing game playback audio",
        "未找到受支持的 FGO 应用，无法限定播放声音来源" to "No supported FGO app found; playback audio source cannot be narrowed",
        "设备不支持 16 kHz 单声道播放声音捕获" to "This device does not support 16 kHz mono playback capture",
        "播放声音捕获初始化失败" to "Playback audio capture failed to initialize",
        "[翻译失败：API 未返回可显示内容]" to "[Translation failed: API returned no displayable content]",
        "[未配置 API Key]\n请打开设置并输入 API Key。" to "[No API key]\nOpen Settings and enter your API key.",
        "中国 Azure 实时翻译需要填写资源端点" to "China Azure live translation requires a resource endpoint",
        "中国 Azure 资源端点格式无效" to "China Azure resource endpoint format is invalid",
        "中国 Azure 资源端点必须使用 HTTPS" to "China Azure resource endpoint must use HTTPS",
        "中国 Azure 资源端点必须是 *.cognitiveservices.azure.cn" to "China Azure resource endpoint must be *.cognitiveservices.azure.cn",
        "中国 Azure 资源端点不能包含账号、端口、查询参数或片段" to "China Azure resource endpoint cannot contain credentials, port, query, or fragment",
        "请填写 Azure 门户显示的资源根端点" to "Enter the resource root endpoint shown in the Azure portal",
        "暂时无法读取版本信息" to "Version information is temporarily unavailable",
        "版本信息格式不正确" to "Version information format is invalid",
        "暂时无法检查版本" to "Unable to check for updates right now",
        "Azure 语音合成失败" to "Azure speech synthesis failed",
        "语音播放失败" to "Voice playback failed",
    )


    private val diagnostic = mapOf(
        "已建立临时语音档案" to "Temporary voice profile created",
        "区域翻译失败" to "Area translation failed",
        "无障碍手势注入不可用" to "Accessibility gesture injection unavailable",
        "无障碍服务已开启但未连接" to "Accessibility service enabled but not connected",
        "无障碍服务已连接" to "Accessibility service connected",
        "无障碍截屏权限失效" to "Accessibility screenshot permission lost",
        "处理流程失败" to "Processing failed",
        "未支持的 FGO 包名" to "Unsupported FGO package",
        "术语库更新失败" to "Glossary update failed",
        "自动侦测循环失败" to "Auto-detection loop failed",
        "找不到语音档案" to "Voice profile not found",
        "实时语音翻译不可用" to "Live voice translation unavailable",
        "临时语音 API 冷却中" to "Temporary voice API cooling down",
        "临时语音档案写入失败" to "Temporary voice profile write failed",
        "临时语音档案读取失败" to "Temporary voice profile read failed",
        "建立临时语音档案失败" to "Failed to create temporary voice profile",
        "语气增强请求失败" to "AI expression request failed",
        "语气增强请求超时" to "AI expression request timed out",
        "语音资料更新失败" to "Voice data update failed",
        "音讯播放无法开始" to "Audio playback cannot start",
        "音讯播放失败" to "Audio playback failed",
        "请求建立临时语音档案" to "Requesting temporary voice profile",
        "截图内容为空（全黑）" to "Screenshot is empty (all black)",
        "截屏失败" to "Screenshot failed",
        "翻译 API 失败" to "Translation API failed",
        "翻译结果悬浮层显示失败" to "Failed to show translation overlay",
        "API返回了不允许的语音模型" to "API returned a disallowed voice model",
        "API返回了不支持的 voice_type" to "API returned an unsupported voice_type",
        "API返回格式不正确" to "API response format is invalid",
        "Azure Speech Key 未设置" to "Azure Speech Key is not set",
        "OCR 识别失败" to "OCR recognition failed",
        "OCR 预载失败" to "OCR preload failed",
        "上次建立失败，暂时不重复请求" to "Last attempt failed; not retrying for now.",
        "已改用本机语气规则" to "Using local expression rules",
        "已是最新" to "Up to date",
        "已是最新版本" to "Up to date",
        "区域翻译覆盖层点击无法转发给 FGO" to "Area translation overlay taps cannot be forwarded to FGO",
        "无障碍截图返回了全黑画面，OCR 无法识别文字" to "Accessibility screenshot returned an all-black frame; OCR could not read text",
        "主语音表与临时语音表都未命中" to "No match in the main or temporary voice table",
        "正在下载术语库" to "Downloading glossary",
        "正在安装术语库" to "Installing glossary",
        "正在更新术语库" to "Updating glossary",
        "正在校验术语库" to "Verifying glossary",
        "正在检查版本" to "Checking for updates",
        "更新完成" to "Update complete",
        "没有可用 TSV 行" to "No usable TSV row",
        "系统仍标记服务为已启用，但 FgoGotran 没有收到连接" to "System still marks the service as enabled, but FgoGotran has not received a connection",
        "系统设置显示已开启，但 FgoGotran 没有收到连接" to "System settings show it as on, but FgoGotran has not received a connection",
        "服务仍显示已连接，但系统拒绝了截屏请求" to "Service still shows connected, but the system denied the screenshot request",
        "检测到疑似 FGO，但包名不在支持列表中" to "Suspected FGO detected, but the package is not in the supported list",
        "翻译覆盖层点击无法转发给 FGO" to "Translation overlay taps cannot be forwarded to FGO",
        "AI语音已开启，但 Azure Speech Key 为空" to "AI voice is on, but Azure Speech Key is empty",
        "Azure 会话已结束" to "Azure session ended"
    )

    private val diagnosticDetails = mapOf(
        "无障碍服务不可用" to "Accessibility service unavailable",
        "未知截屏失败。请确认游戏画面没有黑屏，FgoGotran 无障碍服务仍开启，并尝试重启游戏或模拟器。" to "Unknown screenshot failure. Make sure the game screen is not black, the FgoGotran accessibility service is still on, and try restarting the game or emulator.",
        "关闭无障碍服务，等待 2–3 秒后重新开启，然后回到 FGO 重试" to "Turn off the accessibility service, wait 2–3 seconds, turn it back on, then return to FGO and try again.",
        "多见于模拟器、投屏、黑屏、省电锁屏或显示状态切换。请确认游戏画面实际显示在手机/模拟器主屏上。" to "Often caused by emulators, screen casting, black screens, battery saver lock screens, or display-state changes. Make sure the game is actually visible on the phone or emulator main screen.",
        "多见于模拟器、系统图形层或当前画面状态异常。可尝试重启游戏、重启模拟器，或切换模拟器图形渲染模式。" to "Often caused by emulator or system graphics issues or an abnormal screen state. Try restarting the game or emulator, or switching the emulator graphics renderer.",
        "多见于模拟器图形兼容问题。可尝试切换 DirectX/OpenGL/Vulkan 渲染模式、更新模拟器，或改用 64 位实例。" to "Often caused by emulator graphics compatibility. Try switching DirectX/OpenGL/Vulkan rendering, updating the emulator, or using a 64-bit instance.",
        "多见于模拟器图形渲染异常：请完整重启模拟器，或切换图形渲染模式后再试" to "Often caused by emulator graphics rendering issues. Fully restart the emulator or switch the graphics renderer and try again.",
        "系统标记了安全画面，应用无法读取截图。请避开受保护页面后再试。" to "The system marked this as a secure screen, so the app cannot read screenshots. Leave protected screens and try again.",
        "请关闭无障碍服务，等待 2–3 秒后重新开启；刚切换模拟器图形模式时请完整重启模拟器" to "Turn off the accessibility service, wait 2–3 seconds, and turn it back on; after switching emulator graphics mode, fully restart the emulator.",
        "请关闭并重新开启 FgoGotran 无障碍服务；若系统限制无障碍权限，请在系统设置中允许。" to "Turn the FgoGotran accessibility service off and on again; if the system restricts accessibility, allow it in system settings.",
        "请关闭并重新开启 FgoGotran 无障碍服务；模拟器切换图形模式后需完整重启模拟器" to "Turn the FgoGotran accessibility service off and on again; after switching emulator graphics mode, fully restart the emulator.",
        "请等待约 1 秒后再试；半自动/全自动模式会稍后重试。" to "Wait about 1 second and try again; semi-auto and auto modes will retry later.",
        "截屏请求超时，通常是模拟器图形层或系统繁忙。稍后会自动重试；若持续出现可重启游戏或切换模拟器渲染模式。" to "Screenshot request timed out, usually because the emulator graphics layer or system is busy. It will retry automatically; if it keeps happening, restart the game or switch the emulator renderer.",
        "Android 无法读取当前窗口画面。请回到 FGO 主画面后再试，或重启游戏/模拟器。" to "Android cannot read the current window. Return to the FGO main screen and try again, or restart the game/emulator."
    )

    private val patterns: List<Pair<Regex, (MatchResult) -> String>> = listOf(
        Regex("""^已清除 (\d+) 条缓存$""") to { m -> "Cleared " + m.groupValues[1] + " cache entries" },
        Regex("""^(\d+) 幕$""") to { m -> m.groupValues[1] + " scenes" },
        Regex("""^(.+) 秒$""") to { m -> m.groupValues[1] + " s" },
        Regex("""^发布日期：(.+)$""") to { m -> "Release date: " + m.groupValues[1] },
        Regex("""^当前版本：(.+)$""") to { m -> "Current version: " + m.groupValues[1] },
        Regex("""^最新版本：(.+)$""") to { m -> "Latest version: " + m.groupValues[1] },
        Regex("""^状态：(.+)\n用时：(.+)\n结果：([\s\S]+)$""") to { m ->
            "Status: " + m.groupValues[1] + "\nTime: " + m.groupValues[2] + "\nResult: " + m.groupValues[3]
        },
        Regex("""^测试失败：(.+)$""") to { m -> "Test failed: " + m.groupValues[1] },
        Regex("""^测试语音已播放(.+)$""") to { m -> "Test voice played" + m.groupValues[1] },
        Regex("""^服务商返回错误：(.+)$""") to { m -> "Provider error: " + m.groupValues[1] },
        Regex("""^模型或请求参数不被服务商接受：(.+)$""") to { m -> "Provider rejected the model or request parameters: " + m.groupValues[1] },
        Regex("""^额度或频率限制异常：(.+)$""") to { m -> "Quota or rate limit issue: " + m.groupValues[1] },
        Regex("""^Azure 语音请求失败：(.+)$""") to { m -> "Azure voice request failed: " + m.groupValues[1] },
        Regex("""^可用于 FgoGotran 翻译；接口不接受 (.+)，已自动忽略$""") to { m -> "Works with FgoGotran translation; unsupported parameters ignored: " + m.groupValues[1] },
        Regex("""^自动：Temperature (.+)；不发送 Top-p。$""") to { m -> "Auto: Temperature " + m.groupValues[1] + "; no Top-p." },
        Regex("""^发现新版本 (.+)$""") to { m -> "Update available " + m.groupValues[1] },
        Regex("""^当前版本 (.+)$""") to { m -> "Current version " + m.groupValues[1] },
        Regex("""^截图能力=(.+)，屏幕=(.+)x(.+)$""") to { m -> "Screenshot capability=" + m.groupValues[1] + ", screen=" + m.groupValues[2] + "x" + m.groupValues[3] },
        Regex("""^Android/模拟器没有返回截图：(.+)$""") to { m -> "Android/emulator did not return a screenshot: " + m.groupValues[1] },
        Regex("""^远端版本：(.+)，本地版本：(.+)$""") to { m -> "Remote version: " + m.groupValues[1] + ", local version: " + m.groupValues[2] }
    )

    fun translate(text: String): String? {
        exact[text]?.let { return it }
        diagnostic[text]?.let { return it }
        diagnosticDetails[text]?.let { return it }
        if (text.endsWith("：")) {
            val prefix = text.dropLast(1)
            val translatedPrefix = exact[prefix] ?: diagnostic[prefix] ?: diagnosticDetails[prefix]
            return (translatedPrefix ?: prefix) + ":"
        }
        patterns.forEach { (regex, transform) ->
            val match = regex.matchEntire(text) ?: return@forEach
            return transform(match)
        }
        return null
    }
}




